# Defaults
DEV_ROOT=${HOME}/develop

# Setup dev environment
DEV=${DEV_ROOT}
TOOLS=${DEV}/tools
GROOVYBIN=${TOOLS}/groovy/bin
MAVENBIN=${TOOLS}/maven/bin
GOPATH=${DEV_ROOT}/go-workspace
GOBIN=$(export GOPATH; go env GOPATH)/bin

# specify JAVA_HOME. Since Java 10 is available, I'm going with it
JAVA_HOME=$(/usr/libexec/java_home -v 10)

# Modify the $PATH
PATH=${PATH}:${GROOVYBIN}:${MAVENBIN}:$GOBIN

# load machine specific configuration
if [ -e "${HOME}/Dropbox/Dotfiles/$(hostname -s)" ]; then
  source "${HOME}/Dropbox/Dotfiles/$(hostname -s)"
fi

# Alias definition
for alias in $(find ~/.alias.d/ -type f -not -name .DS_Store)
do
    source "$alias"
done

export PATH JAVA_HOME GOPATH

# Ingo
# setup rbenv
eval "$(rbenv init -)"

# setup pyenv
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi

# setup rvm
#source ${HOME}/.rvm/scripts/rvm

# setup nvm
# source $(brew --prefix nvm)/nvm.sh
# export NVM_DIR=~/.nvm
