## Platform Switch
## the install location of brew on Intel and M1 is different
## Intel= /usr/local/bin/brew
## M1= /opt/homebrew/bin/brew

case "$(uname -m)" in
    "x86_64")
        HOMEBREW_BIN=/usr/local/bin/brew
    ;;
    "arm64")
        HOMEBREW_BIN=/opt/homebrew/bin/brew
    ;;
    *)
        echo "Unsupported architecture"
    ;;
esac

# homebrew
export HOMEBREW_BIN
export HOMEBREW_CELLAR=$(${HOMEBREW_BIN} --cellar)
export HOMEBREW_PREFIX=$(${HOMEBREW_BIN} --prefix)
export HOMEBREW_FPATH=${HOMEBREW_PREFIX}/share/zsh/site-functions

# some tools like fnm wouldn't work without this
export PATH=${HOMEBREW_PREFIX}/bin:${HOMEBREW_PREFIX}/sbin:${PATH}

# Defaults
export DEV_ROOT=${HOME}/develop

# Setup dev environment
export GOVERSION=go@1.22
export GOROOT=$(${HOMEBREW_BIN} --prefix go@1.22) 
export GOPATH=${DEV_ROOT}/go-workspace
# export GOBIN=$(export GOPATH; go env GOPATH)/bin
export GOPROXY=https://proxy.golang.org
export PATH=${PATH}:$GOPATH/bin:$GOROOT/bin

export MACHINE_CONFIG_FILE="${HOME}/Library/Mobile Documents/com~apple~CloudDocs/MachineEnvs/$(hostname -s)"

export PATH="${${HOMEBREW_PREFIX} --prefix openjdk)/bin:$PATH"

# Modify the $PATH
export PATH="${PATH}:/usr/local/sbin:${HOME}/.fastlane/bin:${HOME}/.local/bin"
# ${HOME}/.cargo/bin"

###############################
# EXPORT ENVIRONMENT VARIABLE #
###############################

export EDITOR='nvim'
export TERM='rxvt-256color'
export DOTFILES="$HOME/.dotfiles"
export WORKSPACE="$HOME/workspace"

# Path to your oh-my-zsh installation.
export HOMEBREW_CASK_OPTS="--appdir=/Applications"
export KEYBASE_DIR="/Volumes/Keybase"
export LEDGER_FILE="${KEYBASE_DIR}/private/ingorichter/Finance/2022.journal"

export ZSH_FUNCTIONS="$HOME/.zsh-functions"

# zplug
export ZPLUG_HOME=${HOMEBREW_PREFIX}/opt/zplug
export ZPLUG_FPATH=${ZPLUG_HOME}/repos

# setup fnm
eval "$(fnm env --use-on-cd)"

# Cargo
. "$HOME/.cargo/env"
