# Platform Switch
# the install location of brew on Intel and M1 is different
# Intel= /usr/local/bin/brew
# M1= /opt/homebrew/bin/brew

case "$(uname -m)" in
    "x86_64")
        HOMEBREW_BIN=/usr/local/bin/brew
    ;;
    "arm64")
        HOMEBREW_BIN=/opt/homebrew/bin/brew
    ;;
    *)
        echo "Unsupported architecture"
    ;;
esac

export HOMEBREW_BIN
export HOMEBREW_CELLAR=$(${HOMEBREW_BIN} --cellar)
export HOMEBREW_PREFIX=$(${HOMEBREW_BIN} --prefix)
export HOMEBREW_FPATH=${HOMEBREW_PREFIX}/share/zsh/site-functions

export PATH=${HOMEBREW_PREFIX}/bin:${PATH}

# Defaults
export DEV_ROOT=${HOME}/develop

# Setup dev environment
export GOPATH=${DEV_ROOT}/go-workspace
export GOBIN=$(export GOPATH; go env GOPATH)/bin

export MACHINE_CONFIG_FILE="${HOME}/Dropbox/Dotfiles/$(hostname -s)"

# Modify the $PATH
export PATH="${GOBIN}:/usr/local/sbin:${PATH}:${HOME}/.fastlane/bin:${HOME}/.cargo/bin"

###############################
# EXPORT ENVIRONMENT VARIABLE #
###############################

export TERM='rxvt-256color'
export DOTFILES="$HOME/.dotfiles"
export WORKSPACE="$HOME/workspace"

# Path to your oh-my-zsh installation.
export HOMEBREW_CASK_OPTS="--appdir=/Applications"
export KEYBASE_DIR="/Volumes/Keybase"
export LEDGER_FILE="${KEYBASE_DIR}/private/ingorichter/Finance/2022.journal"

# Make n node version manager work
export N_PREFIX=${HOME}/n
export PATH=${PATH}:${N_PREFIX}/bin

# Cargo
. "$HOME/.cargo/env"